2023-09-10 18:31:49,815 INFO An Info
2023-09-10 18:31:49,816 ERROR An Error
2023-09-10 18:31:50,077 INFO Start polling
2023-09-10 18:31:50,138 INFO Run polling for bot @foodfindbot id=6523255231 - 'Бот'
2023-09-10 18:31:59,004 INFO Update id=774147785 is handled. Duration 324 ms by bot id=6523255231
2023-09-10 18:32:01,627 INFO Update id=774147786 is handled. Duration 95 ms by bot id=6523255231
2023-09-10 18:32:37,602 INFO Update id=774147787 is handled. Duration 157 ms by bot id=6523255231
2023-09-10 18:32:40,718 INFO Update id=774147788 is handled. Duration 201 ms by bot id=6523255231
2023-09-10 18:32:42,784 INFO Update id=774147789 is handled. Duration 180 ms by bot id=6523255231
2023-09-10 18:32:47,684 INFO Update id=774147790 is handled. Duration 323 ms by bot id=6523255231
2023-09-10 18:35:47,793 INFO Update id=774147791 is handled. Duration 563 ms by bot id=6523255231
2023-09-10 18:37:24,949 INFO Update id=774147792 is handled. Duration 161 ms by bot id=6523255231
2023-09-10 18:37:27,758 INFO Update id=774147793 is handled. Duration 92 ms by bot id=6523255231
2023-09-10 19:13:53,590 INFO Update id=774147794 is handled. Duration 166 ms by bot id=6523255231
2023-09-10 20:18:44,182 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
2023-09-10 20:18:44,182 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6523255231)
2023-09-10 20:18:55,307 INFO Connection established (tryings = 1, bot id = 6523255231)
2023-09-10 23:05:25,535 INFO Update id=774147795 is handled. Duration 168 ms by bot id=6523255231
2023-09-10 23:05:31,292 INFO Update id=774147796 is handled. Duration 119 ms by bot id=6523255231
2023-09-10 23:05:33,504 INFO Update id=774147797 is handled. Duration 70 ms by bot id=6523255231
2023-09-10 23:05:36,181 INFO Update id=774147798 is handled. Duration 101 ms by bot id=6523255231
2023-09-10 23:05:39,794 INFO Update id=774147799 is handled. Duration 182 ms by bot id=6523255231
2023-09-11 08:03:16,113 INFO Update id=774147800 is handled. Duration 225 ms by bot id=6523255231
2023-09-11 08:03:18,121 INFO Update id=774147801 is handled. Duration 87 ms by bot id=6523255231
2023-09-11 08:03:20,499 INFO Update id=774147802 is handled. Duration 116 ms by bot id=6523255231
2023-09-11 08:03:22,409 INFO Update id=774147803 is handled. Duration 114 ms by bot id=6523255231
2023-09-11 08:03:31,596 INFO Update id=774147804 is handled. Duration 304 ms by bot id=6523255231
2023-09-11 09:09:38,974 INFO Update id=774147805 is handled. Duration 269 ms by bot id=6523255231
2023-09-11 09:12:52,672 INFO Update id=774147806 is handled. Duration 134 ms by bot id=6523255231
2023-09-11 09:12:59,817 INFO Update id=774147807 is handled. Duration 76 ms by bot id=6523255231
2023-09-11 09:13:29,749 INFO Update id=774147808 is handled. Duration 206 ms by bot id=6523255231
2023-09-11 09:14:49,006 INFO Update id=774147809 is handled. Duration 501 ms by bot id=6523255231
2023-09-11 09:16:02,332 INFO Update id=774147810 is handled. Duration 514 ms by bot id=6523255231
2023-09-11 09:45:46,934 INFO Update id=774147811 is handled. Duration 140 ms by bot id=6523255231
2023-09-11 09:46:11,008 INFO Update id=774147812 is handled. Duration 366 ms by bot id=6523255231
2023-09-11 09:46:12,857 INFO Update id=774147813 is not handled. Duration 71 ms by bot id=6523255231
2023-09-11 09:46:12,857 ERROR Cause exception while process update id=774147813 by bot id=6523255231
ValidationError: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/root/lcbot/bot.py", line 159, in smsc_action
    await callback.message.answer(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/types/message.py", line 1725, in answer
    return SendMessage(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
2023-09-11 09:47:22,740 INFO Update id=774147814 is handled. Duration 238 ms by bot id=6523255231
2023-09-11 09:47:57,339 INFO Update id=774147815 is handled. Duration 491 ms by bot id=6523255231
2023-09-11 09:48:00,006 INFO Update id=774147816 is not handled. Duration 76 ms by bot id=6523255231
2023-09-11 09:48:00,006 ERROR Cause exception while process update id=774147816 by bot id=6523255231
ValidationError: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/root/lcbot/bot.py", line 159, in smsc_action
    await callback.message.answer(
  File "/usr/local/lib/python3.10/dist-packages/aiogram/types/message.py", line 1725, in answer
    return SendMessage(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<function update_ping at 0x7fde565756c0>, input_type=function]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
2023-09-11 09:48:44,784 INFO Update id=774147817 is handled. Duration 335 ms by bot id=6523255231
2023-09-11 11:07:06,261 INFO Update id=774147818 is handled. Duration 215 ms by bot id=6523255231
